In [1]:
#cleaning data, cleaning empty cell,cleaning wrong data,cleaning wrong format,removing duplicate
import pandas as pd

# Creating a Series
data = [10, 20, 30, 40, 50]
s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [2]:
data = {
    'Name': ['Amit', 'Raj', 'Sara'],
    'Age': [25, 30, 22],
    'City': ['Delhi', 'Mumbai', 'Kolkata']
}

df = pd.DataFrame(data)
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 112.0+ bytes
   Name  Age     City
0  Amit   25    Delhi
1   Raj   30   Mumbai
2  Sara   22  Kolkata

In [7]:
df.describe()

             Age
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000

In [14]:
df[["Name","Age"]]

   Name  Age
0  Amit   25
1   Raj   30
2  Sara   22

In [17]:
df.loc[[0,2]]

   Name  Age     City
0  Amit   25    Delhi
2  Sara   22  Kolkata

In [34]:
df.loc[0,"City"]

'Delhi'

In [33]:
df.iloc[0:2,0:1]

   Name
0  Amit
1   Raj

In [5]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Amit', 'Raj', 'Sara'],
    'Age': [25, 30, 22],
    'City': ['Delhi', 'Mumbai', 'Kolkata']
}

df = pd.DataFrame(data)

# Writing DataFrame to CSV
df.to_csv('output.csv', index=False)

print("CSV file saved successfully!")

CSV file saved successfully!

In [40]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Amit', 'Raj', 'Sara', 'Pooja', 'John'],
    'Age': [25, 30, 22, 29, 35],
    'City': ['Delhi', 'Mumbai', 'Kolkata', 'Pune', 'Chennai']
}

df = pd.DataFrame(data)

# Filter rows where Age >20
filtered_df = df[df['Age'] >25]
print(filtered_df)

    Name  Age     City
1    Raj   30   Mumbai
3  Pooja   29     Pune
4   John   35  Chennai

In [41]:
df[(df['Age'] > 25) & (df['City'] == 'Mumbai')]

  Name  Age    City
1  Raj   30  Mumbai

In [42]:
df[(df['Age'] > 25) | (df['City'] == 'Delhi')]

    Name  Age     City
0   Amit   25    Delhi
1    Raj   30   Mumbai
3  Pooja   29     Pune
4   John   35  Chennai

In [44]:
df.query("Age > 25 ")

    Name  Age     City
1    Raj   30   Mumbai
3  Pooja   29     Pune
4   John   35  Chennai

In [47]:
print(df.isnull().sum())

Name    0
Age     0
City    0
dtype: int64

In [64]:
import pandas as pd
import numpy as np

# Sample DataFrame with NaN values
data = {
    'Name': ['Amit', 'Raj', 'Sara', 'Pooja', 'John'],
    'Age': [25, np.nan, 22, 29, np.nan],
    'City': ['Delhi', 'Mumbai', np.nan, 'Pune', 'Chennai']
}

df = pd.DataFrame(data)

# Check missing values
print(df.isna())  
df.fillna(0, inplace=True)
df

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

    Name   Age     City
0   Amit  25.0    Delhi
1    Raj   0.0   Mumbai
2   Sara  22.0        0
3  Pooja  29.0     Pune
4   John   0.0  Chennai

In [61]:
df.dropna(inplace=True)
df

    Name   Age   City
0   Amit  25.0  Delhi
3  Pooja  29.0   Pune

In [62]:
df.dropna(subset=['Name'], inplace=True)
df

    Name   Age   City
0   Amit  25.0  Delhi
3  Pooja  29.0   Pune

    Name   Age   City
0   Amit  25.0  Delhi
3  Pooja  29.0   Pune

In [1]:
import pandas as pd
data = {
    'Age': ['25', '30', '22', '29'],
    'Salary': ['50000', '60000', '45000', '70000'],
    'Join_Date': ['2024-03-01', '2023-06-15', '2022-08-10', '2021-11-20']
}

df = pd.DataFrame(data)
print(df.dtypes)
df

Age          object
Salary       object
Join_Date    object
dtype: object

  Age Salary   Join_Date
0  25  50000  2024-03-01
1  30  60000  2023-06-15
2  22  45000  2022-08-10
3  29  70000  2021-11-20