In [1]:
import pandas as pd

### Series

In [42]:
sales=pd.Series([1,2,None,4,5])
sales.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [19]:
#index
print(sales[0])

2

In [5]:
sale=pd.Series([[1,2,3],[4,5,3]])
data=pd.Series(["a","b","s",'c'])
print(data.sort_values())

0    a
1    b
3    c
2    s
dtype: object

In [57]:
#print(sale.index)
#print(sale.values)
#sale.dtype
#print(sale.head(1))
print(data.info())

<class 'pandas.core.series.Series'>
Index: 2 entries, name to age
Series name: None
Non-Null Count  Dtype
--------------  -----
2 non-null      object
dtypes: object(1)
memory usage: 32.0+ bytes
None

In [7]:
df = pd.DataFrame(sale.to_dict())
df

   0  1
0  1  4
1  2  5
2  3  3

In [74]:
sales.sort_values()
#sales.count()

0    1.0
1    2.0
3    4.0
4    5.0
2    NaN
dtype: float64

In [8]:
#checking missing values
sales.isnull()
sales.notnull()

0    True
1    True
2    True
3    True
dtype: bool

In [9]:
#airthemtic operations
sales +1
sales**2

0     4
1     1
2     9
3    16
dtype: int64

In [10]:
series=pd.Series([1,2,3,None])
series.notnull()
#series.fillna(5,inplace=True)
series.fillna(5)
series

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [11]:
series=series.fillna(5)
series

0    1.0
1    2.0
2    3.0
3    5.0
dtype: float64

In [82]:
s1=pd.Series(data=[2,3,4,5,6],index=list("abcde"))

In [90]:
s1 = pd.Series(data=[1,2,3,4,5])
s2 = pd.Series(data=[10,20,30,40,50])
df = pd.DataFrame({'C2':s1, 'C1':s2})
df

    C2    C1
a  2.0   NaN
b  3.0   NaN
c  4.0   NaN
d  5.0   NaN
e  6.0   NaN
0  NaN  10.0
1  NaN  20.0
2  NaN  30.0
3  NaN  40.0
4  NaN  50.0

C2    5
C1    5
dtype: int64

# Dataframe

In [66]:
data=pd.DataFrame({'name':[None,'sabu'],
                  'age':[22,32]})

In [67]:
salary=pd.Series([2000,4000])
data["salary"]=salary
data

   name  age  salary
0  None   22    2000
1  sabu   32    4000

In [43]:

#making dataframe by series by combining them both
s1=pd.Series([2,3,4,5,6])
s2=pd.Series([3,3,4,5,6])
data1=pd.DataFrame({'c1':s1,'c2':s2})

In [44]:
print(data.shape)
data.columns

(2, 3)

Index(['name', 'age', 'salary'], dtype='object')

In [45]:
data.loc[0,'name']

'nabu'

In [46]:
data.iloc[0,0]

'nabu'

In [47]:
#methods
data.head()
data.tail(1)
data.count()
#data.info()
print(data.describe()) 
#data.sort_values(by='age')

             age       salary
count   2.000000     2.000000
mean   27.000000  3000.000000
std     7.071068  1414.213562
min    22.000000  2000.000000
25%    24.500000  2500.000000
50%    27.000000  3000.000000
75%    29.500000  3500.000000
max    32.000000  4000.000000

In [48]:
#condtional
data[data['age']>30]

   name  age  salary
1  sabu   32    4000

In [49]:
data.loc[2] = ['bishu', 30,888]

In [50]:
data["salary"]=[1200,2000,3000]

In [51]:
#del data["salary"]
data.drop(columns=['salary'],inplace=True)
data

    name  age
0   nabu   22
1   sabu   32
2  bishu   30

In [52]:
data.loc[data['age'] == 32, 'age'] = 22
data

    name  age
0   nabu   22
1   sabu   22
2  bishu   30

In [58]:
data.rename(columns={"name":"naam"},inplace=True)

In [59]:
data.set_index('naam',inplace=True)

KeyError: "None of ['naam'] are in the columns"

In [61]:
data.reset_index(inplace=True)
data

   index   naam  age
0      0   nabu   22
1      1   sabu   22
2      2  bishu   30

In [33]:
#multi index
#multidata=pd.dataframe({}).set_index([name of columns])

    naam  age  salary
0   nabu   22    1200
1   sabu   22    2000
2  bishu   30    3000

In [2]:
#query
#df.query("age>30")

# Working with data

In [3]:
'''data.to_csv("file_name.csv")
data=pd.read_csv(file_name)'''

'data.to_csv("file_name.csv")\ndata=pd.read_csv(file_name)'

In [11]:
import numpy as np
df={'x':[1,2,3],'y':np.array([1,2,3]),'z':50}

In [12]:
pd.DataFrame(df)

   x  y   z
0  1  1  50
1  2  2  50
2  3  3  50

In [18]:
f=[[1,2,3],[10,40,30],[50,20,30]]
pd.DataFrame(f,columns=['x','y','z'])

    x   y   z
0   1   2   3
1  10  40  30
2  50  20  30

In [21]:
na=np.array([[1,2,3],[2,3,4],[3,5,6]])
a=pd.DataFrame(na)

In [27]:
#giving name to columns
a.columns=["a",'b','c']
a

   a  b  c
0  1  2  3
1  2  3  4
2  3  5  6

In [32]:
a['b'].value_counts()

b
2    1
3    1
5    1
Name: count, dtype: int64

### Data Cleaning and preprocessing

In [68]:
# handling missing values/data
#data.dropna()
series=pd.DataFrame([1,2,3,None])
#series.dropna()
data.dropna(subset=["name"],inplace=True)
data

   name  age  salary
1  sabu   32    4000

In [69]:
#aggregrate methods
series.mean()
series.fillna(series.mean())
series.fillna(series.std())
series.fillna(series.min())
series.fillna(series.max())
series.fillna(series.var())
series.fillna(series.median())

     0
0  1.0
1  2.0
2  3.0
3  2.0

In [50]:
f=[[1,2,3],[10,40,30],[50,None,30]]
f=pd.DataFrame(f,columns=['x','y','z'])

In [55]:
f['y'].mean()

In [57]:
f['y'].fillna(f['y'].mean())

0     2.0
1    40.0
2    21.0
Name: y, dtype: float64

In [84]:
# duplicates
s1=pd.Series([3,3,4,6,6])
s2=pd.Series([3,3,4,5,6])
data1=pd.DataFrame({'c1':s1,'c2':s2})
#data1.drop_duplicates(inplace=True)
#data1.drop_duplicates(inplace=True,subset=["c1"])
data1.iloc[:-2]

   c1  c2
0   3   3
1   3   3
2   4   4

In [85]:
#replace value
data1.replace(3,100)

    c1   c2
0  100  100
1  100  100
2    4    4
3    6    5
4    6    6

In [75]:
#type_conversion
data1['c1']=data1['c1'].astype(float)

In [79]:
data1['c3']=["yes",'no','yy','no']
data1['c3'].str.upper()

0    YES
2     NO
3     YY
4     NO
Name: c3, dtype: object

### Data aggreation and grouping

In [153]:
#group by
# grouped=data.groupby("Name")
s1=pd.Series(['a','b','a','a','b'])
s2=pd.Series([3,3,4,5,6])
data1=pd.DataFrame({'name':s1,'lemonglass':s2})
data1

  name  lemonglass
0    a           3
1    b           3
2    a           4
3    a           5
4    b           6

In [154]:
group=data1.groupby('name')
print(group.sum())
group['lemonglass'].mean()
group['lemonglass'].max()

      lemonglass
name
a             12
b              9

name
a    5
b    6
Name: lemonglass, dtype: int64

In [90]:
#pivottable
data1.pivot_table(values='lemonglass',index='name')

      lemonglass
name
a            4.0
b            4.5

In [94]:
#cross tab
pd.crosstab(data1["name"],data1['lemonglass'])

lemonglass  3  4  5  6
name
a           1  1  1  0
b           1  0  0  1

### merging,joining,concat

In [104]:
# adding of 2 dataframe
#pd.concat([dataframe1,dataframe2])
s=pd.Series(['a','b','a','a','b'])
s=pd.Series([3,3,4,5,6])
data=pd.DataFrame({'name':s1,'lemonglass':s2})
s1=pd.Series([3,3,4,6,6])
s2=pd.Series([3,3,4,5,6])
data1=pd.DataFrame({'h':s1,'c2':s2})
d=data.reset_index(drop=True)
d1=data1.reset_index(drop=True)
pd.concat([d,d1],axis=1)

   name  lemonglass  h  c2
0     3           3  3   3
1     3           3  3   3
2     4           4  4   4
3     6           5  6   5
4     6           6  6   6

In [3]:
df=pd.DataFrame({"name":["navdeep","karan","abhishek"],
                "age":[22,34,45],})
df1=pd.DataFrame({"name":["ashu","arnav","shivam"],
                 "fees":[322,4090,5409]})
df.reset_index(drop=True,inplace=True)
df1.reset_index(drop=True,inplace=True)
a=pd.concat([df,df1])

In [4]:
r=a.loc[:,~a.columns.duplicated()]

In [118]:
#merge,should have common column #innerjoin
pd.merge(df,df1,on='name')

       name  age  fees
0   navdeep   22   322
1     karan   34  4090
2  abhishek   45  5409

In [6]:
#join on index# left join internally
#data.join(data1.set_index('name'),on='name')

### working with timeseries data

In [1]:
import pandas as pd
data = {
    'Age': ['25', '30', '22', '29'],
    'Salary': ['50000', '60000', '45000', '70000'],
    'Join_Date': ['24-03-01', '23-06-15', '22-08-10', '21-11-20']
}

df = pd.DataFrame(data)
df.loc[1,"Age"]="33"
df

  Age Salary Join_Date
0  25  50000  24-03-01
1  33  60000  23-06-15
2  22  45000  22-08-10
3  29  70000  21-11-20

In [2]:
df['Join_Date']=pd.to_datetime(df['Join_Date'])
df

C:\Users\maman\AppData\Local\Temp\ipykernel_10076\1565724366.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Join_Date']=pd.to_datetime(df['Join_Date'])

  Age Salary  Join_Date
0  25  50000 2001-03-24
1  33  60000 2015-06-23
2  22  45000 2010-08-22
3  29  70000 2020-11-21

In [3]:
df.set_index('Join_Date',inplace=True)
df

           Age Salary
Join_Date
2001-03-24  25  50000
2015-06-23  33  60000
2010-08-22  22  45000
2020-11-21  29  70000

In [4]:
#conerting string to dates
import pandas as pd
pd.to_datetime('2025-04-29')

Timestamp('2025-04-29 00:00:00')

In [7]:
#data resampling 
#df.resample('W').sum() #1 weeek ko ek date mai bata dete hai
#df.resample("M").sum() #last day of the month
#df.resample("A").sum()

In [43]:
#df.groupby('column_name') with agg function
import pandas as pd
import numpy as np
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'salary': [40000, 50000, 42000, 52000, 60000, 58000]
}

df = pd.DataFrame(data)

In [44]:
#df["salary"]=np.where(df["Department"]=="IT",df["salary"],df["salary"]+100)
df.loc[df["Department"] == "IT", "salary"]+=1000
df

  Department Employee  salary
0         HR        A   40100
1         IT        B   50000
2         HR        C   42100
3         IT        D   52000
4    Finance        E   60100
5    Finance        F   58100

In [161]:
df.groupby('Department')['Salary'].sum()

Department
Finance    118000
HR          82000
IT         102000
Name: Salary, dtype: int64

In [162]:
df.groupby('Department')['Employee'].count()

Department
Finance    2
HR         2
IT         2
Name: Employee, dtype: int64

In [163]:
df.groupby('Department')['Salary'].agg(['mean', 'min', 'max', 'count'])

               mean    min    max  count
Department
Finance     59000.0  58000  60000      2
HR          41000.0  40000  42000      2
IT          51000.0  50000  52000      2

In [166]:
df.groupby(['Department', 'Employee'])['Salary'].sum()

Department  Employee
Finance     E           60000
            F           58000
HR          A           40000
            C           42000
IT          B           50000
            D           52000
Name: Salary, dtype: int64

In [169]:
grouped_df = df.groupby('Department', as_index=False)['Salary'].mean()
print(grouped_df)

  Department   Salary
0    Finance  59000.0
1         HR  41000.0
2         IT  51000.0

In [170]:
df.groupby('Department')['Salary'].apply(lambda x: x.max() - x.min())

Department
Finance    2000
HR         2000
IT         2000
Name: Salary, dtype: int64

In [19]:
data = {'Date': ['20-12-2025', '20-01-2010', '20-02-2005'],
    'Sales': [2500, 4000, 3200]
}
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date']) 
df

C:\Users\maman\AppData\Local\Temp\ipykernel_9056\4146667528.py:5: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

        Date  Sales
0 2025-12-20   2500
1 2010-01-20   4000
2 2005-02-20   3200

In [20]:
df['Year'] = df['Date'].dt.year
df['Month_Year'] = df['Date'].dt.strftime('%b-%Y')
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.day_name()
df

        Date  Sales  Year Month_Year  Month  Day    Weekday
0 2025-12-20   2500  2025   Dec-2025     12   20   Saturday
1 2010-01-20   4000  2010   Jan-2010      1   20  Wednesday
2 2005-02-20   3200  2005   Feb-2005      2   20     Sunday

In [8]:
df[df['Date'].dt.month == 1]

        Date  Sales  Year  Month  Day Weekday
1 2025-01-10   4000  2025      1   10  Friday

In [21]:
pd.date_range(start='2025-01-01', end='2025-10-10')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10',
               ...
               '2025-10-01', '2025-10-02', '2025-10-03', '2025-10-04',
               '2025-10-05', '2025-10-06', '2025-10-07', '2025-10-08',
               '2025-10-09', '2025-10-10'],
              dtype='datetime64[ns]', length=283, freq='D')

In [38]:
df = pd.DataFrame({
    'Timestamp': ['2025-01-10 08:30:00', '2025-01-10 15:45:00']
})

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['Hour'] = df['Timestamp'].dt.hour
df

            Timestamp  Hour
0 2025-01-10 08:30:00     8
1 2025-01-10 15:45:00    15

In [40]:
df['Hour'] = df['Timestamp'].dt.hour
df

            Timestamp  Hour
0 2025-01-10 08:30:00     8
1 2025-01-10 15:45:00    15

In [43]:
df['current']=pd.Timestamp.now().date()
df

            Timestamp  Hour Hour min  Minute  Second     current
0 2025-01-10 08:30:00     8    08:30      30       0  2026-02-02
1 2025-01-10 15:45:00    15    15:45      45       0  2026-02-02

In [45]:
df['Hour'] = df['Timestamp'].dt.hour
df['Hour min'] = df['Timestamp'].dt.strftime("%H:%M")
df['Minute'] = df['Timestamp'].dt.minute
df['Second'] = df['Timestamp'].dt.second
df

            Timestamp  Hour Hour min  Minute  Second     current
0 2025-01-10 08:30:00     8    08:30      30       0  2026-02-02
1 2025-01-10 15:45:00    15    15:45      45       0  2026-02-02

In [47]:
df = pd.DataFrame({
    'Start': ['2025-01-01', '2025-02-01'],
    'End': ['2026-10-10', '2011-11-20']
})

df['Start'] = pd.to_datetime(df['Start'])
df['End'] = pd.to_datetime(df['End'])

df['Duration'] = (df['End'] - df['Start'])
df['monthDuration']=((df['End'].dt.year -  df["Start"].dt.year))#*12+(df['End'].dt.month -  df["Start"].dt.month))
df

       Start        End   Duration  monthDuration
0 2025-01-01 2026-10-10   647 days              1
1 2025-02-01 2011-11-20 -4822 days            -14

In [2]:
import pandas as pd

data = {
    'Name': ['Amit', 'Ravi', 'Neha', 'Amit', 'Ravi', 'Simran'],
    'Marks': [85, 90, 92, 85, 90, 95]
}

df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit     85
1    Ravi     90
2    Neha     92
3    Amit     85
4    Ravi     90
5  Simran     95

In [ ]:
df.duplicated()

In [3]:
df[df.duplicated()]
df[~df.duplicated()]
df.duplicated(subset=['Name'])

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [46]:
df[["Department",'salary']]

  Department  salary
0         HR   40100
1         IT   50000
2         HR   42100
3         IT   52000
4    Finance   60100
5    Finance   58100

In [48]:
df['salary'].unique()

array([40100, 50000, 42100, 52000, 60100, 58100])

In [49]:
len(df)

6

In [100]:
df=pd.read_csv("amazon_sales_dataset.csv")
df.head(2)
df.tail(2)

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16
49999,50000,2023-06-29,2944,Home & Kitchen,253.44,30,1,Europe,Debit Card,2.1,464,177.41,177.41

In [13]:
df["order_date"]=pd.to_datetime(df["order_date"])

In [14]:
df.groupby("product_category")["price"].sum()

product_category
Beauty            2136610.77
Books             2104086.91
Electronics       2095753.12
Fashion           2110890.01
Home & Kitchen    2095984.71
Sports            2082037.48
Name: price, dtype: float64

In [6]:
df.groupby("product_category")["discount_percent"].count()

product_category
Beauty            8465
Books             8327
Electronics       8320
Fashion           8365
Home & Kitchen    8258
Sports            8265
Name: discount_percent, dtype: int64

In [7]:
#d=df[df["discount_percent"] > 20]
#df.groupby("product_category")["discount_percent"].apply(lambda x: (x > 10).sum())
df.groupby("customer_region")["customer_region"].count()

customer_region
Asia             12526
Europe           12452
Middle East      12505
North America    12517
Name: customer_region, dtype: int64

In [103]:
#df["current"]=pd.Timestamp.now()
#df[df["current"].dt.year-df["order_date"].dt.year<4]

#df.loc[(df["product_category"] == "Fashion") & (df["price"] > 300), "price"]+=100
#df["product_category"].where(df["price"]>300,)
df[df["price"] > 300]["product_category"]
df[df["price"] > 300]
#df["high_price_category"] = df["product_category"].where(df["price"] > 300, "Low Price")
#df["price"].where(df["price"] > 300, inplace=True)

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
5,6,2023-12-02,1777,Sports,385.17,30,3,Asia,Wallet,3.8,489,269.62,808.86
8,9,2022-05-02,3262,Books,373.62,0,4,Asia,Wallet,2.8,497,373.62,1494.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49986,49987,2022-11-07,4956,Electronics,338.40,5,4,Asia,Wallet,4.4,410,321.48,1285.92
49991,49992,2023-06-26,1809,Electronics,489.56,10,2,Europe,Credit Card,2.8,218,440.60,881.20
49993,49994,2022-09-04,3615,Sports,306.98,15,2,North America,Wallet,4.8,438,260.93,521.86
49997,49998,2023-02-17,4651,Electronics,352.11,30,4,Asia,Debit Card,3.1,104,246.48,985.92
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16

In [91]:
df[(df["product_category"].isin(["Fashion","Sports"])) & (df["price"]>300)&(df["quantity_sold"]>3)].sort_values(by="price",ascending=True)

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
49605,49606,2023-08-05,4905,Fashion,300.11,5,5,Middle East,Credit Card,1.3,151,285.10,1425.50
44719,44720,2023-12-29,4130,Fashion,300.15,10,4,Asia,UPI,4.9,76,270.14,1080.56
48614,48615,2022-09-05,4173,Fashion,300.18,10,5,North America,Cash on Delivery,4.9,484,270.16,1350.80
48539,48540,2022-08-23,1729,Fashion,300.25,5,5,Asia,Credit Card,3.9,431,285.24,1426.20
9063,9064,2023-10-29,3937,Fashion,300.27,20,4,Europe,Cash on Delivery,3.9,460,240.22,960.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20520,20521,2023-08-18,2758,Sports,499.67,20,5,North America,Wallet,1.1,12,399.74,1998.70
5422,5423,2023-01-23,2118,Fashion,499.75,5,4,North America,Cash on Delivery,3.6,25,474.76,1899.04
4849,4850,2023-03-26,1114,Sports,499.82,30,5,North America,UPI,4.3,274,349.87,1749.35
20629,20630,2023-03-19,1314,Fashion,499.87,5,4,North America,Credit Card,4.5,460,474.88,1899.52
27832,27833,2022-03-04,3821,Sports,499.91,0,5,North America,Wallet,1.8,230,499.91,2499.55

In [31]:
#df[["product_id","price"]]

In [43]:
#df.nlargest(5, "price")
df.nsmallest(5, "price")
df["order_date"] = pd.to_datetime(df["order_date"])
df[df["order_date"] > "2020-01-01"]

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,current
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,2026-02-02 13:43:31.852119
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40,2026-02-02 13:43:31.852119
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28,2026-02-02 13:43:31.852119
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64,2026-02-02 13:43:31.852119
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72,2026-02-02 13:43:31.852119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2022-09-03,1433,Beauty,26.99,0,5,Middle East,Credit Card,2.4,386,26.99,134.95,2026-02-02 13:43:31.852119
49996,49997,2022-07-03,1428,Beauty,294.23,10,5,Asia,Credit Card,3.1,8,264.81,1324.05,2026-02-02 13:43:31.852119
49997,49998,2023-02-17,4651,Electronics,352.11,30,4,Asia,Debit Card,3.1,104,246.48,985.92,2026-02-02 13:43:31.852119
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16,2026-02-02 13:43:31.852119
49999,50000,2023-06-29,2944,Home & Kitchen,253.44,30,1,Europe,Debit Card,2.1,464,177.41,177.41,2026-02-02 13:43:31.852119

In [52]:
#df.select_dtypes(include="number")
#pd.pivot_table(df, index='product_category', values='price', aggfunc='mean')

In [86]:
dff=pd.read_csv("sales_data.csv")
dff["Order Date"]=pd.to_datetime(dff["Order Date"])

In [87]:
dff.groupby(["Product Name","Category"])["Quantity"].agg(["sum","count"])
dff

     Order Date Product Name     Category Region  Quantity  Sales   Profit
0    2024-12-31      Printer       Office  North         4   3640   348.93
1    2022-11-27        Mouse  Accessories   East         7   1197   106.53
2    2022-05-11       Tablet  Electronics  South         5   5865   502.73
3    2024-03-16        Mouse  Accessories  South         2    786   202.87
4    2022-09-10        Mouse  Accessories   West         1    509   103.28
...         ...          ...          ...    ...       ...    ...      ...
3495 2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496 2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497 2022-04-12       Laptop  Electronics  South         4    260    66.02
3498 2022-01-18      Printer       Office  South         3    222    50.28
3499 2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]

In [109]:
d1=pd.read_csv("delhi_traffic_target.csv")
d1

         Trip_ID  travel_time_minutes
0     TRIP_00001                 15.3
1     TRIP_00002                  3.0
2     TRIP_00003                 92.7
3     TRIP_00004                 10.6
4     TRIP_00005                 42.0
...          ...                  ...
3995  TRIP_03996                 76.8
3996  TRIP_03997                 37.2
3997  TRIP_03998                 30.9
3998  TRIP_03999                 27.6
3999  TRIP_04000                 64.6

[4000 rows x 2 columns]