In [41]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\maman\Downloads\Telegram Desktop\car_dataset.csv")
df

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [22]:
df.drop("3",axis=1,inplace=True)
df

,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,168.80,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [55]:
df=df.drop("?",axis=1)
df

KeyError: "['?'] not found in axis"

In [53]:
df.columns = [ "Brand", "Fuel Type", "Aspiration", "Num of Doors", "Body Style", "Drive Wheels", "Engine Location", "Wheelbase", "Length", "Width", "Height", "Curb Weight", "Engine Type", "Num of Cylinders", "Engine Size", "Fuel System", "Bore", "Stroke", "Compression Ratio", "Horsepower","Peak RPM", "City"," MPG", "Highway MPG", "Price"]
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City,MPG,Highway MPG,Price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [54]:
df.replace("?",np.nan,inplace=True)
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City,MPG,Highway MPG,Price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [44]:
df.isnull().sum()

3              0
alfa-romero    0
gas            0
std            0
two            2
convertible    0
rwd            0
front          0
88.60          0
168.80         0
64.10          0
48.80          0
2548           0
dohc           0
four           0
130            0
mpfi           0
3.47           4
2.68           4
9.00           0
111            2
5000           2
21             0
27             0
13495          4
dtype: int64

In [57]:
df["Num of Doors"].replace(np.nan,"two",inplace=True)
df

TypeError: Could not convert mpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfi2bbl2bbl2bbl2bbl2bblmpfi2bbl2bbl2bblmpfi2bblmfi1bbl1bbl1bbl1bbl1bbl1bbl1bbl1bbl1bbl1bbl1bblmpfi2bbl2bbl2bbl2bblspfimpfimpfimpfi2bbl2bbl2bbl2bbl2bbl4bbl4bbl4bblmpfi2bbl2bbl2bbl2bblidi2bblmpfiidiidiidiidiidimpfimpfimpfimpfimpfi2bbl2bbl2bblspdispdi2bblspdispdispdi2bbl2bblspdispdi2bblidi2bbl2bbl2bbl2bbl2bbl2bbl2bbl2bbl2bbl2bblmpfimpfimpfimpfimpfimpfimpfiidimpfiidimpfiidimpfiidimpfiidimpfi2bblspdi2bbl2bbl2bbl2bblspdimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfi2bbl2bbl2bbl2bbl2bblmpfi2bblmpfi2bblmpfi2bblmpfi2bbl2bbl2bbl2bbl2bbl2bbl2bbl2bblidiidi2bbl2bbl2bbl2bbl2bblmpfimpfimpfimpfimpfimpfimpfimpfimpfiidimpfimpfimpfimpfimpfimpfimpfiidimpfiidimpfimpfiidimpfimpfimpfimpfiidimpfimpfimpfimpfimpfimpfimpfimpfimpfimpfiidimpfi to numeric

KeyError: 'Bore'